services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: sisters-api
    volumes:
      - ./cmd/sisters:/go/src/cmd/sisters
      - ./pkg:/go/src/pkg/
      - ./internal:/go/src/internal/
      - ./tmp/:/go/src/tmp/
      
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: sisters-api
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080

networks:
  sisters-network:
    driver: bridge
