version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: sisters-api
    volumes:
      - ./cmd/sisters:/go/src/app/cmd/
      - ./pkg:/go/src/app/pkg/
      - ./internal:/go/src/app/internal/
      - ./docker/images:/go/src/app/docker/images/
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: backend
    restart: always
    tty: true
    ports:
      - 8080:8080

networks:
  db-network:
    driver: bridge
