name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
      - name: Download Go modules
        shell: bash
        if: ${{setups.setup-go.outputs.cache-hit != 'true'}}
        run: go mod download
      - name: Build
        run: go build -v
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "--timeout 3m0s"
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
      - name: Run test
        run: go test -v ./...
